image: java:8

before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew -g /cache./gradle check

deploy:
  stage: deploy
  script:
    - ./gradlew -g /cache/.gradle clean build
    - mv cgc/build/distributions/cgc.zip .
  allow_failure: false
  artifacts:
    paths:
      - cgc.zip
  only:
    - tags
